//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace randevu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arac_tbl
    {
        public int AracId { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public Nullable<short> ModelYili { get; set; }
        public string Yakit { get; set; }
        public string Vites { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
    }
}
