//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace randevu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AracımızEntities : DbContext
    {
        public AracımızEntities()
            : base("name=AracımızEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Arac_tbl> Arac_tbl { get; set; }
        public virtual DbSet<Musteri_tbl> Musteri_tbl { get; set; }
        public virtual DbSet<Rezervasyon_tbl> Rezervasyon_tbl { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
    }
}
